- link:
    ~/.zshrc: shells/zsh/zshrc.workstation.zsh
    ~/.zshenv: shells/zsh/zshenv.workstation.zsh
    ~/.zprofile: shells/zsh/zprofile.workstation.zsh
    ~/.p10k.zsh: shells/zsh/p10k.workstation.zsh
    ~/.dotfiles/shells/zsh/custom/aliases.zsh: shells/zsh/aliases.workstation.zsh