- link:
    ~/.zshrc: shells/zsh/zshrc.personal.zsh
    ~/.zshenv: shells/zsh/zshenv.personal.zsh
    ~/.zprofile: shells/zsh/zprofile.personal.zsh
    ~/.p10k.zsh: shells/zsh/p10k.personal.zsh
    ~/.gruvbox.dircolors: shells/zsh/gruvbox.dircolors
