- defaults:
    link:
      create: true
      relink: true
      force: true

- clean: ['~']

- link:
    ~/.iterm2_shell_integration.zsh: apps/iterm2/iterm2_shell_integration.zsh
    ~/.latexmkrc: misc/latexmkrc

- shell:
    - ["git submodule update --init --recursive", "Installing submodules"]
